# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       blts-tracker-perf

# >> macros
# << macros

Summary:    BLTS tracker performance test suite
Version:    0.0.1
Release:    0
Group:      Development/Testing
License:    GPLv2
URL:        https://github.com/mer-qa/blts-tracker-perf
Source0:    %{name}-%{version}.tar.gz
Source100:  blts-tracker-perf.yaml
Requires:   dbus-x11
Requires:   tracker
Requires:   tracker-tests

%description
This package contains tracker performance tests


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
mkdir -p %{buildroot}/opt/tests/blts-tracker-perf
install --mode=644 common.sh %{buildroot}/opt/tests/blts-tracker-perf
install --mode=755 test-indexing.sh %{buildroot}/opt/tests/blts-tracker-perf
install --mode=644 test-storage-io.cnf %{buildroot}/opt/tests/blts-tracker-perf
install --mode=755 test-storage-io.sh %{buildroot}/opt/tests/blts-tracker-perf
install --mode=644 tests.xml %{buildroot}/opt/tests/blts-tracker-perf
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
/opt/tests/blts-tracker-perf/*
# >> files
# << files
